#!/bin/sh

# Temporarily add Git Bash to PATH if it's not already in the PATH
if ! command -v bash &> /dev/null
then
    export PATH="$PATH:/c/Program Files/Git/usr/bin"
fi

# Форматируем файлы и добавляем изменения в коммит
npm run prettier:write -- --no-color
git add -u
