name: Check Code

permissions:
  contents: read # access to check out code and install dependencies

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  node-install:
    name: Prepare MPM cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci

  prettier:
    name: Check formatting
    needs: node-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run prettier:check

  typescript:
    name: Check types
    needs: node-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run typescript:check
